
workflow:
    - second
shared:
    image: node:6
jobs:
    main:
        steps:
            - sleep: sleep 10
            - print: echo Starting main job!
    second:
        steps:
            - print: echo Starting second job!
