
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - test: sd-step exec core/git git clone git@github.com:minz1027/hook-demo.git
            - echo: echo hello
            - print: echo the main jobs started!
            - check-go-img: go version
    publish:
        steps:
            - echo: echo $SD_TOKEN
