
settings:
    slack:
      url: https://hooks.slack.com/services/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
      statuses:
        - SUCCESS
        - FAILURE
    
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - test-success: echo hello

