
shared:
    description: 'hi!'
    image: node:6
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - sleep: sleep 1000
            - test-mount: echo faketoken > /sd/token
            - docker: docker run -v /sd/token/:/tmp/token/ ubuntu cat /tmp/token
            - docker-ps: docker ps -a
  
