shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        annotations:
            beta.screwdriver.cd/timeout: 30
        requires: [~pr, ~commit]
        steps:
            - jwt: echo $SD_TOKEN
            - set: sleep 10000
            - get: meta get foo
