
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        requires: [~commit, ~pr]
        steps:
            - print: echo running main
    other_main:
        requires: ~commit
        steps:
            - print: echo running other_main
            - extra_stuff: echo crazy stuff here
    publish:
       requires: main
       steps:
           - print: echo running publish
    other_publish:
       requires: other_main
       steps:
           - print: echo running other_publish
           - extra_stuff: echo crazy stuff here
