shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        annotations:
            screwdriver.cd/buildPeriodically: '20 * * * *'
        requires: [~pr, ~commit]
        steps:
            - set: meta set foo sd175
            - get: meta get foo
