
workflow:
    - publish
shared:
    image: docker-registry.ops.yahoo.com:4443/sd_platform/cookbook-chefdk:5.0.6
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - write: echo 'secret' > /tokens/ntoken
            - test: echo $PREFIX && echo $PREFIX2
            - sleep: sleep 500
            - py: python ./config.py
            - meta: meta set foo bar
            - meta-get: meta get foo
            - echo: echo hello
        environment: 
            PREFIX: beta-
            PREFIX2: 'beta-'
    publish:
        steps:
            - echo: echo $SD_TOKEN
