
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    detached:
        steps:
            - meta get foo bar
    detached_second:
        requires: detached
        steps:
            - meta get foo
    source_main:
        sourcePaths: ["README.md"]
        requires: [~commit, ~pr]
        settings:
            slack: 
              - test-slack-notif
              - test-slack-min
        steps:
            - cat: cat access_log
    main:
       image: python
       requires: [~pr,~commit]
       steps:
           - test: |
                foo | echo "a"
                echo "bar"
           - echo: echo $SD_PIPELINE_NAME && sleep 100
   
    job2:
        requires: main
        steps:
            - hab: ls /hab/pkgs/core
            - meta: meta set foo bar
            - write: echo 'aa' > /sd/meta/test.json

    job3:
        requires: job2
        steps:
            - echo: echo hello

    job4:
        requires: job3
        steps:
            - echo: echo hello

    job5:
        requires: job4
        steps:
            - echo: echo hello
