
workflow:
    - publish
shared:
    image: node:6
jobs:
    main:
        steps:
            - install: npm install
    publish:
        steps:
            - semantic-release: npm run semantic-release
        secrets:
            - GH_TOKEN
            - NPM_TOKEN
