
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - test: find . -name "*" -type f -exec curl -H "Authorization: Bearer $SD_TOKEN" -H "Content-Type: text/plain" -X PUT https://store.screwdriver.cd/v1/builds/$SD_BUILD_ID/ARTIFACTS/{} -T {} \
            - echo: echo $SD_TOKEN
            - print: echo the main jobs started!
            - check-go-img: go version
    publish:
        steps:
            - echo: echo $SD_TOKEN
