
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        annotations:
            beta.screwdriver.cd/executor: queue
        steps:
            - ls: ls
    publish:
        steps:
            - meta-get: /opt/sd/meta get foo
            - echo: echo $SD_TOKEN
