shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
    settings:
        slack:
          url: https://hooks.slack.com/services/
          statuses:
            - SUCCESS
            - FAILURE
        
jobs:
    main:
        steps:
            - test-success: echo hello
            - meta: meta set foo bar
            - meta-get: meta get foo

