
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - pwd: pwd
            - clone: git clone https://github.com/tk3fftk/meta-cli.git $GOPATH/src/github.com/screwdriver-cd/meta-cli
            - cd: cd $GOPATH/src/github.com/screwdriver-cd/meta-cli
            - checkout: git checkout meta-cli
            - go-get: go get -t ./...
            - build: go build -a -o meta-cli
            - mk: mkdir /sd/meta
            - run: chmod 777 /sd/meta
            - set: ./meta-cli set foo bar &&  echo $?
            - get: export FOO=./meta-cli get foo && echo $FOO
            - run-e: chmod 000 /sd/meta
            - set-ag: ./meta-cli set x bar &&  echo $?
            - get-ag: ./meta-cli get x
            - print: echo the main jobs started!
            - check-go-img: go version
    publish:
        steps:
            - install: npm install
            - echo: echo $SD_TOKEN
            - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
            - release: ./ci/git-release.sh
        secrets:
            - GITHUB_TOKEN
        environment:
            RELEASE_FILE: README.md
