
workflow:
    - publish
shared:
    image: node:6
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - write: mkdir -p /sd/tokens
            - test: echo $PREFIX && echo $PREFIX2
            - sleep: sleep 5
            - py: python ./config.py
            - meta: meta set foo bar
            - meta-get: meta get foo
            - echo: echo hello
        environment: 
            PREFIX: beta-
            PREFIX2: 'beta-'
    publish:
        steps:
            - echo: echo $SD_TOKEN
