
shared:
    image: golang:latest
    environment:
        GOPATH: /sd/workspace
        
jobs:
    detached:
        steps:
            - meta get foo bar
    detached_second:
        requires: detached
        steps:
            - meta get foo
    source_main:
        sourcePaths: ["README.md"]
        requires: [~commit, ~pr]
        settings:
            slack: 
              - test-slack-notif
              - test-slack-min
        steps:
            - cat: cat access_log
    main:
       image: python
       requires: [~pr,~commit]
       steps:
           - test: |
                foo | echo "a"
                echo "bar"
           - echo: echo $SD_PIPELINE_NAME
   
