shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - set: meta set foo bar
            - get: meta get foo
    second:
        requires: main
        steps:
            - get: meta get foo

