
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - ls: ls
            - show: /opt/sd/meta
            - set: /opt/sd/meta set foo bar &&  echo $?
            - get: /opt/sd/meta get foo
            - cat: cat /sd/meta/meta.json
            - print: echo the main jobs started!
            - check-go-img: go version
    publish:
        steps:
            - meta-get: /opt/sd/meta get foo
            - echo: echo $SD_TOKEN
