
mysteps:
   - test2: &test2 echo from mysetp

shared:
    description: 'hi!@@'
    image: node:6
    steps:
      - test1: echo shared
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - test: *test2


  
