
shared:
    description: 'hi!@@'
    image: golang:latest
    steps:
      - test1: &test1 echo shared
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - print: echo Starting main jo
