shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        annotations:
            beta.screwdriver.cd/timeout: 1
        requires: [~pr, ~commit]
        steps:
            - set: sleep 500
            - get: meta get foo
