
shared:
    description: 'hi!@@'
    image: node:6
    steps:
      - test1: &test1 echo shared
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - test: *test1


  
