
workflow:
    - publish
shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - show: ./meta
            - set: ./meta set foo bar &&  echo $?
            - get: ./meta get foo && echo $?
            - append-newline: echo "\n" >> /sd/meta/meta.json
            - cat: cat /sd/meta/meta.json
            - chmod-000: chmod 000 /sd/meta/meta.json
            - set-again: ./meta set x bar && echo $?
            - get-again: ./meta get x && echo $?
            - cat-again: cat /sd/meta/meta.json && echo $?
            - print: echo the main jobs started!
            - check-go-img: go version
    publish:
        steps:
            - install: npm install
            - echo: echo $SD_TOKEN
            - setup-ci: git clone https://gist.github.com/3d2388b2a7ba658cdcdaffa8cd874e50.git ci
            - release: ./ci/git-release.sh
        secrets:
            - GITHUB_TOKEN
        environment:
            RELEASE_FILE: README.md
