annotations:
    beta.test: 123

shared:
    image: golang
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - set: meta set foo bar
            - get: meta get foo
    second_main:
        requires: [main, ~sd@175:main]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main
    third:
        requires: [main]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main
            - exit: exit 1
    last:
        requires: [second_main,third]
        steps:
            - get: meta get foo && meta get foo --external sd@175:main

