
shared:
    description: 'hi!@@'
    image: golang:latest
    steps:
      - test1: &test1 echo shared
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            # - hab: /opt/sd/bin/hab pkg install core/git
            - echo: echo hello


  
