
workflow:
    - publish
shared:
    image: node:6
    environment:
        GOPATH: /sd/workspace
        
jobs:
    main:
        steps:
            - test-step: sd-step exec core/git "git clone --quiet --progress https://github.com/minz1027/waffle.git"
            - cd-list: cd waffle && ls
            - test-step-rest: sd-step exec core/git 'git reset --hard 123a8089d002754d2f99ef2d2a30f1f51a62ece9'
            - list-env: env
            - write: mkdir -p /sd/tokens
            - test: echo $PREFIX && echo $PREFIX2
            - sleep: sleep 5
            - py: python ./config.py
            - meta: meta set foo bar
            - meta-get: meta get foo
            - echo: echo hello
        environment: 
            PREFIX: beta-
            PREFIX2: 'beta-'
    publish:
        steps:
            - echo: echo $SD_TOKEN
